### ISSUE TITLE
This assembly need to reference at least Cake.Core version 0.26.0. 

### ISSUE THREAD

**Issue by jwickowski** [cake-contrib/Cake.MsDeploy#29]
Hi I have an error when i try to run MsDeploy. I worked correctly a week ago.

Cake.exe : Error: The assembly 'Cake.MsDeploy, Version=0.4.0.0, Culture=neutral, PublicKeyToken=null' 
At C:\Projects\Tazos\IsTabeBusy\Deployment\packages\deploy.ps1:234 char:1
+ &$CAKE_EXE $cakeArguments
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Error: The asse...KeyToken=null' :String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
is referencing an older version of Cake.Core (0.22.0). 
This assembly need to reference at least Cake.Core version 0.26.0. 
Another option is to downgrade Cake to an ea
rlier version. 
It's not recommended, but you can explicitly opt-out of assembly verification 
by configuring the Skip Verification setting to true
(i.e. command line parameter "--settings_skipverification=true", 
environment variable "CAKE_SETTINGS_SKIPVERIFICATION=true", 
read more about configuration at https://cakebuild.net/docs/fundamentals/configuration)

**Comment by gep13** [comment]
@jwickowski as per the recommendation in the error message, there is a workaround which you can follow while waiting for this.

On top of this, we recommend that you ALWAYS pin to a specific version of Cake, so that you don't hit this type of issue.

You can find more information about this recommendation here:

https://cakebuild.net/docs/tutorials/pinning-cake-version

**Comment by jwickowski** [comment]
thank you.

**Comment by gep13** [comment]
I think that this is still a valid issue to keep open.
